server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.springcloud.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/*.xml                       # mapper映射文件
spring:
#  security:
#    user:
#       name: kimi
#       password: 233
  application:
    name: microservicecloud-dept
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource           # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8              # 数据库名称
    username: root
    password: 323900llmT
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  instance:
    hostname: localhost    #hostname: eureka7001.com #eureka服务端的实例名称
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址
  client: #客户端注册进eureka服务列表内
    register-with-eureka: true #是否注册到eureka服务器
    fetch-registry: true #是否可检索
    service-url:
      defaultZone: http://localhost:7001/eureka   # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
info:
  app:
    name: kimi-microservicecloud
#  company:
#    name: www.kimi.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$
